name: Sheduled update

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 4,10,16,22, * * *'

  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: restore timestamps
        uses: chetan/git-restore-mtime-action@v2

      # Runs a set of commands using the runners shell
      - name: Run update
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          ./update.sh
